<?php
echo '<h1 id="companyName">The JLW Company<span id="trade_mark">&#8482</span></h1>
        <nav id="navCenter">
            <a class="header-main-nav" href="index.php">Home</a>
            <a class="header-main-nav" href="jobs.php">Jobs</a>
            <a class="header-main-nav" href="apply.php">Apply Now</a>
            <a class="header-main-nav" href="about.php">About Us</a>
            <a class="header-main-nav" href="enhancements.php">Enhancements</a>
        </nav>
<hr>';
?>